---
kitchen:
  log_level: debug

driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
- name: Win2k12r2SQL
  driver_config:
    box: Win2k12r2SQL
    guest: :windows
    customize:
      memory: 4096
    network:
    - ["forwarded_port", {guest: 3389, host: 3389}]
    - ["forwarded_port", {guest: 5985, host: 5985}]
    gui: :true
suites:
- name: default
  run_list:
    - 'recipe[tbi-sqlserver::default]'
  attributes:
    chef_client:
      config:
        log_level: ":debug"
    sql_server:
      version: '2012'
