---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
- name: Win2k12r2SQL
  driver_config:
    box: Win2k12r2SQL
    guest: :windows
    network:
    - ["forwarded_port", {guest: 3389, host: 3389}]
    - ["forwarded_port", {guest: 5985, host: 5985}]
suites:
- name: default
  run_list:
    - 'recipe[tbi-sqlserver::default]'
  attributes:
